version: '3.5'

services:

  pubsubly-service:
    image: "waggins/pubsubly-service:v4"
    networks:
      - service-pubsubly-network
    ports:
      - "9000:9000"
    volumes:
      - ./config:/config
    environment:
      - SPRING_CONFIG_LOCATION=file:/config/application-local.yml
      - SPRING_PROFILES_ACTIVE=example

  pubsubly-ui:
    image: "waggins/pubsubly-ui:v2"
    networks:
      - service-pubsubly-network
    ports:
      - "3001:3001"
    links:
      - pubsubly-service
    depends_on:
      - pubsubly-service

networks:
  service-pubsubly-network:
    external:
      name: pubsubly-network