name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build Pubsubly API with Maven
        run: mvn -B install --file ./pubsubly-api/pom.xml
      - name: Deploy Pubsubly API with Maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir ~/.m2
          cat ~/.m2/settings.xml
          echo "<settings><servers><server><id>github</id><username>wkennedy</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
          mvn --settings settings.xml deploy --file ./pubsubly-api/pom.xml
      - name: Build Pubsubly Redis Message Header Plugin with Maven
        run: mvn -B install --file ./redis-message-header-plugin/pom.xml
      - name: Build Pubsubly Service with Maven
        run: mvn -B package --file ./pubsubly-service/pom.xml
