name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: ${{ env.NRM_USER }}
          server-password: ${{ env.NRM_PASS }}
      - name: Build Pubsubly API with Maven
        run: mvn -B install --file ./pubsubly-api/pom.xml
      - name: Deploy Pubsubly API with Maven
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NRM_USER: ${{ secrets.OSSRH_USERNAME }}
          NRM_PASS: ${{ secrets.OSSRH_TOKEN }}
        run:
          mvn deploy --file ./pubsubly-api/pom.xml
#      - name: Build Pubsubly Redis Message Header Plugin with Maven
#        run: mvn -B install --file ./redis-message-header-plugin/pom.xml
#      - name: Build Pubsubly Service with Maven
#        run: mvn -B package --file ./pubsubly-service/pom.xml
